### ISSUE TITLE
Tweak.xm:80: error: %orig found outside of hook or subclass

### ISSUE THREAD

**Issue by akrl** [andugu/ScreenChat#1]
I get this error when running "make package"

/Users/****/Desktop/sc/ScreenChat/theos/makefiles/targets/Darwin/iphone.mk:41: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
Making all for tweak ScreenChat...
 Preprocessing Tweak.xm...
Tweak.xm:80: error: %orig found outside of hook or subclass
make[2]: *** [obj/Tweak.xm.a25c1306.o] Error 22
make[1]: *** [internal-library-all_] Error 2
make: *** [ScreenChat.all.tweak.variables] Error 2

**Comment by akrl** [comment]
Last commit fixed the issue.

**Comment by andugu** [comment]
Yup, sorry. Put an space between % and hook. Fixed :)
