### ISSUE TITLE
Patched APP crashes on start - Library not loaded: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate

### ISSUE THREAD

**Issue by urosch** [andugu/ScreenChat#2]
Using iOS 9.2.1 iPhone 5. I've tried everything I could find on the internet...
Like this one-didn't work:
[https://github.com/BishopFox/theos-jailed/issues/6]

Dyld Message: Library not loaded: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate

Referenced from: /var/mobile/Containers/Bundle/Application/97C98524-3EFE-40DD-980D-77C2553A39C4/Snapchat.app/ScreenChat.dylib
  Reason: image not found
  Dyld Version: 370.6

**Comment by andugu** [comment]
I never had any problem like this, are you using a decrypted ipa file? And from where did you get it?

**Comment by urosch** [comment]
Yes, the ipa is decrypted... Got it from "app addict". I can try another source later today and report back.

**Comment by urosch** [comment]
Nope, same error on crashing. Used appcake source this time...

**Comment by andugu** [comment]
Pm me on reddit, I will compile the ipa for you :)

**Comment by urosch** [comment]
:) just PM'd you.

**Comment by andugu** [comment]
Just send the link :+1:

**Comment by urosch** [comment]
There is a slight difference. This time I get:
Dyld Message: Library not loaded: @executable_path/CydiaSubstrate
  Referenced from: /var/mobile/Containers/Bundle/Application/CFB206AC-578E-4C93-A5FA-AD95E47778EC/Snapchat.app/ScreenChat.dylib
  Reason: no suitable image found.  Did find:
	/var/mobile/Containers/Bundle/Application/CFB206AC-578E-4C93-A5FA-AD95E47778EC/Snapchat.app/CydiaSubstrate: mmap() errno=1 validating first page of '/var/mobile/Containers/Bundle/Application/CFB206AC-578E-4C93-A5FA-AD95E47778EC/Snapchat.app/CydiaSubstrate'
	/private/var/mobile/Containers/Bundle/Application/CFB206AC-578E-4C93-A5FA-AD95E47778EC/Snapchat.app/CydiaSubstrate: mmap() errno=1 validating first page of '/private/var/mobile/Containers/Bundle/Application/CFB206AC-578E-4C93-A5FA-AD95E47778EC/Snapchat.app/CydiaSubstrate'
  Dyld Version: 370.6

**Comment by andugu** [comment]
That's really wierd, what provisioning profile are you using? Have you configured it like the patchapp-2.sh says?

**Comment by andugu** [comment]
That's really wierd, what provisioning profile are you using? Have you configured it like the patchapp-2.sh says?

**Comment by urosch** [comment]
Yes. I suspect there is something wrong with my provisioning profile...  I can send you a link to my ipa if it helps in finding a reason for this not working for me.
Otherwise I followed the patchapp-2.sh instructions all the way through.

**Comment by andugu** [comment]
As you used the ipa I compiled, I really think the problem is with the profile. Have you tried to sideload any other app on the device?

**Comment by urosch** [comment]
Yes. All the sideloaded apps work without a problem... I tried the decrypted ipas and also apps from source code. And they all work flawlessly...
Btw, is there a reason my patched ipa gives error:
"Library not loaded: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate"
Because your patched ipa gives me this: 
"Library not loaded: @executable_path/CydiaSubstrate"

**Comment by urosch** [comment]
Did it! Haven't tried the tweak inside app yet but the app isn't crashing anymore on start. ;)
I had to replace the lib folder inside theos. Something must have gotten corrupt inside it. Otherwise I did all the same as previously. Will report back when I check the rest. Thanks for your help again :)

**Comment by urosch** [comment]
Yes. Its really working :) 👍👌

**Comment by andugu** [comment]
Glad to hear! But what did you exactly? Maybe someone can follow the steps in the future.

**Comment by urosch** [comment]
I had to replace the "lib" folder inside theos-jailed folder with the original one - from github. Maybe I corrupted/mixed the files inside it sometime in the past, trying different tweaks and CydiaSubstrates.
So, if you just use the original "lib" file, all should be fine ;)

**Comment by hoangpx** [comment]
do you mean you replaced libsubstrate.dylib ?
