### ISSUE TITLE
-(CGFloat) maxTextWidth method doesn't work

### ISSUE THREAD

**Issue by steexd** [andugu/ScreenChat#3]
Hi,
this method is not working (only for me?) with the last version of SC (9.27.5.0).
With class dump it looks like a "- (long long)maxTextWidth", so I thought that a "return LLONG_MAX" would have fixed the issue, however the caption text limit is still there...

**Comment by andugu** [comment]
It isn't working at all, I tested all the possible values to return the max number of characters of a CGFloat and any of them work. They must changed something.

**Comment by iMokhles** [comment]
[Fixed Here](https://github.com/andugu/ScreenChat/pull/4)
